### ISSUE TITLE
Debugging python code in hook files

### ISSUE THREAD

**Issue by romansklenar** [apiaryio/dredd-hooks-python#10]
When I'm writing hooks in python I sometimes make syntax error or other python error in my hook file.
When I run dredd with this hook file, it's not very verbose and it makes debugging what's wrong in hooks really hard.

This is the example how output looks like in these cases:

```
Configuration dredd.yml found, ignoring other arguments.
info: Beginning Dredd testing...
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /usr/local/lib/node_modules/dredd/node_modules/spawn-sync/error.log for more details
Spawning `python` hooks handler
Error connecting to the hook handler. Is the handler running?
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```
Note: file `/usr/local/lib/node_modules/dredd/node_modules/spawn-sync/error.log` doesn't exist.

From `ECONNREFUSED` I assume that what really happens is that [Dredd hooks handler client](https://dredd.readthedocs.org/en/latest/hooks-new-language/) is not able to connect port 61321 where it should be running because python code from hook file contaning typo/error can't be interpreted.

__So the question is__: Is there a way how can I debug python code in hook file(s) or get more verbose info about error in my hook files?

**Comment by honzajavorek** [comment]
@romansklenar Thanks for the report! This is a very good question.

--------------

First, I think the initial part of output isn't related to your hooks, but to version of your node installation. I filed a separate issue for it: https://github.com/apiaryio/dredd/issues/335

```
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /usr/local/lib/node_modules/dredd/node_modules/spawn-sync/error.log for more details
```

-----------------

This part is relevant:

```
Spawning `python` hooks handler
Error connecting to the hook handler. Is the handler running?
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

Unfortunately, as you correctly assumed, it seems Dredd just tries to connect to hooks and fails. It's quite logical though as Dredd has no information about hooks status before it can connect to them.

To prevent errors in your hooks code, I'd suggest using:

- **Lint:** Use [linter](https://pypi.python.org/pypi/flake8).
- **Check Syntax:** To catch syntax errors, use Python interpreter to run the file with hooks:
    - `python hooks.py` (good enough if there are just hooks in the file and nothing executes during import time)
    - `python -m py_compile hooks.py` (bulletproof - doesn't run the file, just executes it)
- **Test:** If your code gets more complicated, use [unittest](https://docs.python.org/3/library/unittest.html) or [pytest](http://pytest.org/latest/) to test the hooks without Dredd. If you don't feel like using full-fledged testing framework, leveraging `if __name__ == '__main__':` should still allow you to do the simplest checks:
        ```python
        @hooks.before_all
        def foo(transactions):
            ...

        if __name__ == '__main__':
            # testing if my hook correctly sets 'application/json' content type
            transactions = [...]
            foo(transactions)
            assert transactions[...][...] == 'application/json'
        ```

        This way the hooks can be verified just by running `python hooks.py`, in this case both checked syntactically and tested.

**Comment by romansklenar** [comment]
Sure you are right with 2 parts of output. FYI the first part of output is relevant to node v0.10.25 in my case.
Thank you Honza for pointing out the direction. I think I'm able to solve my problem that way.
:100:

**Comment by honzajavorek** [comment]
Great! I still think we should add at least some pointers to docs. Filing https://github.com/apiaryio/dredd/issues/336 and closing this one. Thanks!
