### ISSUE TITLE
Idea: Allow multiple hook decorators to decorate one function

### ISSUE THREAD

**Issue by romansklenar** [apiaryio/dredd-hooks-python#11]
### Before
```python
@hooks.before('Group Members > Group Members resource > Add Member to Group')
def seed_user_for_group(transaction):
    helpers.seed_user(helpers.generate_fake_credentials())

@hooks.before('Group Members > Group Members resource > Remove Member from Group')
def seed_members_in_group(transaction):
    helpers.seed_group_members()

@hooks.before('Group Members > Group Members resource > Promote Member')
def seed_members_for_promotion_in_group(transaction):
    helpers.seed_group_members()

@hooks.before('Group Members > Group Members resource > Demote Member')
def seed_members_for_demotion_in_group(transaction):
    helpers.seed_group_members()
```

### After
```python
@hooks.before('Group Members > Group Members resource > Add Member to Group')
def seed_user_for_group(transaction):
    helpers.seed_user(helpers.generate_fake_credentials())

@hooks.before('Group Members > Group Members resource > Remove Member from Group')
@hooks.before('Group Members > Group Members resource > Promote Member')
@hooks.before('Group Members > Group Members resource > Demote Member')
def seed_members_in_group(transaction):
    helpers.seed_group_members()
```

**Comment by honzajavorek** [comment]
If you just want to stay DRY, you should be able to do this:

```python
def seed_members_in_group(transaction):
    helpers.seed_group_members()

hooks.before('Group Members > Group Members resource > Remove Member from Group')(seed_members_in_group)
hooks.before('Group Members > Group Members resource > Promote Member')(seed_members_in_group)
hooks.before('Group Members > Group Members resource > Demote Member')(seed_members_in_group)
```

Of course, your solution is nicer!

**Comment by romansklenar** [comment]
Thanks for tip! :+1:

**Comment by romansklenar** [comment]
@w-vi Do you think this would be possible to implement?
If you give me a hint, I can try it (not a python dev).

**Comment by honzajavorek** [comment]
@romansklenar It's possible to implement this, but it would require a major redesign of how Python hooks work right now. The decorator internally assigns a property to the function, e.g. `f.dredd_hook = BEFORE_EACH` and then all the functions are automagically loaded.

What we would need to do is to have decorators as "registrators" of the function, so they would do something like `list_of_hooks.append(f)` (`list_of_hooks` is just dummy name I just made up) and then following code would use these lists instead of looking for functions automagically.

**Comment by romansklenar** [comment]
Thanks for response @honzajavorek.
So I'll leave it as it is now - I don't have a python skills and confidence to do major redesign like this.

**Comment by w-vi** [comment]
I'm totally up for this feature, but as @honzajavorek  said it needs a big change in architecture and there is just not enough time right now. But leaving this open as I'd like to see this feature live.

**Comment by honzajavorek** [comment]
Just for the record, I'm also for this feature. Once there'll be a bit of
time for Python hooks, I'll try to implement it.
