### ISSUE TITLE
Report size zero after using python dredd hooks

### ISSUE THREAD

**Issue by KevinKeyflow** [apiaryio/dredd-hooks-python#9]
Hi, when I use dredd without python hooks, it works perfect with a report file in .md format;
but when I add the hooks in command line with option --hookfiles=myhookfile.py,
it will only create a new .md file with size zero and "Hook handler exited with status: null" appears when dredd program terminated, which is not seen when used without python hooks.
Am I doing something wrong?

**Comment by w-vi** [comment]
Hi @KevinKeyflow , it looks like the python hooks handler fails for some reason, what version of python are you using?

**Comment by KevinKeyflow** [comment]
It's 2.7.10.
Thank you!

**Comment by KevinKeyflow** [comment]
btw, the hooks handler work perfectly as usual,
it's just a problem of generating the report file.

**Comment by w-vi** [comment]
Oh, than it's maybe a dredd issue, let me dig a bit deeper into to it, I'll get to it during this week and let's see.

**Comment by w-vi** [comment]
So after some investigation I can confirm that it is a dredd issue and it is happening not only with markdown reporter but generally any file based reporter. There is a synchronization issue where the report file is created but the process is exited before the data are written. I have created a [dredd issue ](https://github.com/apiaryio/dredd/issues/263)

**Comment by w-vi** [comment]
Hi @KevinKeyflow please can you grab the latest [Dredd](https://github.com/apiaryio/dredd) from master and verify that the reporter works as you'd expect i.e. there is a content in the file?

**Comment by KevinKeyflow** [comment]
Yes, it works. Thanks.
